### PR TITLE
#131,#103: Change State Class to Total from Total Increasing.

### PR DESCRIPTION
**Pull request by arosboro**
This will fix the issues reported in #131 and #103 

I verified the historical data still exists.  There is no need to reconfigure the HACS addon for HA Emporia Vue and no need to reconfigure the energy dashboard.

### CODE REVIEW

**Comment by arosboro** [comment]
I'm still testing this.  My total increasing usage went up 65 kWh after making the change.

**Comment by magico13** [comment]
I've actually already made this change in the current pre-release. You are correct, when you load it for the first time after making the change you will need to manually remove the duplicated data from your statistics, or just upgrade at midnight to prevent it.

**Comment by arosboro** [comment]
@magico13 Hi Michael thanks for this great HA add-on, allowing emporia vue owners to take advantage of the Energy reporting features recently added to core.

Do you have a query on a sketch or something you rely on that you had used to do this pruning in the past?  If so would you mind sharing it?

I will close this PR and possibly evaluate your pre-release.  If I notice anything significant, I will provide feedback in the issue queue.

**Comment by magico13** [comment]
Home Assistant 2022.4 added the ability to edit statistics, so you can use that functionality to remove the bad data. https://www.home-assistant.io/blog/2022/04/06/release-20224/#adjusting-long-term-statistics

**Pull request closed without merging**
